# Exported from Render on 2025-08-24T18:00:32Z
services:
- type: web
  name: Erimuga-backend
  runtime: node
  repo: https://github.com/Space-Xplorer/Erimuga
  plan: free
  envVars:
  - key: NODE_ENV
    sync: false
  - key: FRONTEND_URL
    sync: false
  - key: BASE_URL
    sync: false
  - key: RAZORPAY_KEY_SECRET
    sync: false
  - key: RAZORPAY_KEY_ID
    sync: false
  - key: SESSION_SECRET
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: CLOUDINARY_NAME
    sync: false
  - key: CLOUDINARY_API_SECRET
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  - key: MONGODB_URI
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
  autoDeployTrigger: commit
  rootDir: server
version: "1"
